apiVersion: v1
kind: Service
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  selector:
    component: back
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http